- id: https://doi.org/10.7554/eLife.82587
  image: https://iiif.elifesciences.org/lax:82587%2Felife-82587-fig3-v3.tif/full/1500,/0/default.jpg
  
- id: https://doi.org/10.7554/eLife.38841
  image: https://iiif.elifesciences.org/lax/38841%2Felife-38841-fig6-v2.tif/full/1500,/0/default.jpg
