- id: https://doi.org/10.7554/eLife.82587
  image: https://iiif.elifesciences.org/lax:82587%2Felife-82587-fig3-v3.tif/full/1500,/0/default.jpg
  repo: https://github.com/mhturner/glom_pop
  tags:
    - Drosophila
    - Imaging
    - Natural scenes
    
- id: https://doi.org/10.7554/eLife.38841
  image: https://iiif.elifesciences.org/lax/38841%2Felife-38841-fig6-v2.tif/full/1500,/0/default.jpg
  repo: https://github.com/mhturner/CenterSurroundInteractions
  tags:
    - Retina
    - Electrophysiology
    - Natural scenes

- id: https://doi.org/10.7554/eLife.70611
  image: https://iiif.elifesciences.org/lax/70611%2Felife-70611-fig8-v2.tif/full/1500,/0/default.jpg
  tags:
    - Retina
    - Electrophysiology
    - Natural scenes

- id: https://doi.org/10.1016/j.cub.2021.07.051
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982221010411-gr1.jpg
  tags:
    - Drosophila
    - Review
    - AI

- id: https://doi.org/10.1016/j.cub.2021.03.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982221003432-gr2.jpg
  tags:
    - Drosophila
    - Connectome

    
- id: https://doi.org/10.1038/s41593-018-0284-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41593-018-0284-0/MediaObjects/41593_2018_284_Fig5_HTML.png?as=webp
  tags:
    - Review
    - Natural scenes
    - AI
